version: '3'

services:

  ##############################################################
  #                      mongo DB container                    #
  ##############################################################
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: chatapp
      MONGO_INITDB_ROOT_PASSWORD: chatapp


  ##############################################################
  #                   mongo-express container                  #
  ##############################################################
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: chatapp
      ME_CONFIG_MONGODB_ADMINPASSWORD: chatapp
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
